/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.user2310214.view;

import com.user2310214.model.Book;
import com.user2310214.repository.BookRepository;
import com.user2310214.service.BookService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tracy
 */
public class Interfaz extends javax.swing.JFrame {

        String url = "jdbc:mysql://localhost:3306/library";
        String user = "root";
        String password = "Tracy997570268";
        
        
    public Interfaz() {
             try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
          } catch (Exception e) {
            e.printStackTrace();
         }
        initComponents();
        ObtenerLista();
        
    }
    
    
    void ObtenerLista() {
        
         BookRepository repository = new BookRepository(url, user, password);
         
         List<Book> List = repository.findAll();
         
         DefaultTableModel dtm = new DefaultTableModel();
         String titulos[]={"ID","Titulo","Autor","Genero","Año"};
         dtm.setColumnIdentifiers(titulos);
         jtabla.setModel(dtm);
         
         // Borramos si tiene algo la tabla
          int cantFilas = dtm.getRowCount();
        if (cantFilas>0){
            for(int i=0;i<cantFilas;i++){
                dtm.removeRow(0);
            }
        }
        
        String datos[] = new String[10];
         
         for (Book book : List) {
                 datos[0] = String.valueOf(book.getId());
                 datos[1] = book.getTitle();
                 datos[2] = book.getAuthor();
                 datos[3] = book.getGenre();
                 datos[4] = String.valueOf(book.getYear());
                 dtm.addRow(datos);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtautor = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txtannio = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jLabel2.setText("Año:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        jLabel3.setText("Titulo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        jLabel5.setText("Genero:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));
        jPanel1.add(txtautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 300, -1));
        jPanel1.add(txtgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, -1));
        jPanel1.add(txtannio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, -1));
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 300, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 580, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
                BookRepository repository = new BookRepository(url, user, password);
                Book book1 = new Book.BookBuilder()
                .setTitle(txttitulo.getText())
                .setAuthor(txtautor.getText())
                .setGenre(txtgenero.getText())
                .setYear(Integer.parseInt(txtannio.getText()))
                .build();
                
        repository.save(book1);
        JOptionPane.showMessageDialog(rootPane, "Libro Creado");
        ObtenerLista();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Error al crear el libro");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
          int fila = jtabla.getSelectedRow();
        String id =jtabla.getValueAt(fila, 0).toString();
        
        try {
            BookRepository repository = new BookRepository(url, user, password);
             
            repository.delete(Integer.parseInt(id));
            JOptionPane.showMessageDialog(rootPane, "Libro Eliminado");
            ObtenerLista();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al eliminar el libro");
        }
        
       
    }//GEN-LAST:event_jtablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField txtannio;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
